---
# Install ClickHouse using Homebrew
- name: Install ClickHouse
  homebrew:
    name: clickhouse
    state: present
  become: no

# Verify ClickHouse installation
- name: Verify ClickHouse installation
  command: clickhouse-server --version
